[package]
name = "serde-defmt"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
unicode-ident = "1.0.12"

[dev-dependencies]
pretty_assertions = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_path_to_error = "0.1.15"
